#! /bin/sh

name='Abel Tasman - Torrent Bay to Tonga'
scale="1:35000"
chart_no="NZ6144"

kappath=/usr/local/share/charts/LINZ/NewZealand
proj=2193
chart_prefix=$chart_no-EPSG-$proj
chart=$chart_prefix.tiff

gpxpath=. #/home/stephen/projects/gps/tracks
gpxfile=holux-1000c-00.1B.C1.06.F5.80-20131220_2219.gpx
tracks="holux-1000c-00.1B.C1.06.F5.80-20131220_2219.gpx holux-1000c-00.1B.C1.06.F5.80-20131221_1958.gpx"

rm -rf $chart
gdalwarp -of GTiff -t_srs EPSG:$proj $kappath/$chart_no.kap $chart

for track in $tracks; do
   rm -rf $track.EPSG-$proj
   gdal_translate -of GTiff -scale 0 255 0 0 $chart $chart_prefix-$track.tiff
   ogr2ogr -t_srs EPSG:$proj  $track.EPSG-$proj $track tracks
   gdal_rasterize -b 1 -burn 2  -l tracks $track.EPSG-$proj $chart

   # Rasterize onto a white chart
   # TODO: Work out how to make it transparent.
   gdal_translate -of GTiff -scale 0 255 0 0 $chart $chart_prefix-$track.tiff
   gdal_rasterize -b 1 -burn 8  -l tracks $track.EPSG-$proj $chart_prefix-$track.tiff
done

rm -rf "$name.png"
convert \
   -size 2240x3508 xc:white \
   -density 300x300 \
       "$chart[2080x3148+4700+5500]" -geometry +80+60    -composite \
       "$chart[2072x60+4700+594]"    -geometry +80+0     -composite \
       "$chart[2072x60+4700+12336]"  -geometry +80+3208  -composite \
       "$chart[80x3148+427+5500]"    -geometry +0+60     -composite \
       "$chart[80x3148+7999+5500]"   -geometry +2152+60  -composite \
   -stroke black -fill none \
   -draw "polyline 80,60 2152,60 2152,3208 80,3208 80,60" \
   -stroke black -fill black \
   -font 'Helvetica-Bold' \
   -pointsize 16 \
   -annotate +80+3325 "$name"  \
   -font 'Helvetica' \
   -pointsize 8 \
   -annotate +1500+3320 "(from $chart_no. Not to be used for navigation.)" \
   "$name.png"

