#! /bin/sh

name='Abel Tasman - Torrent Bay to Tonga'
scale="1:35000"
source="NZ 6144"

convert \
   -size 2240x3508 xc:white \
   -density 300x300 \
       "png/NZ6144.png[2080x3148+4700+5500]" -geometry +80+60    -composite \
       "png/NZ6144.png[2072x60+4700+594]"    -geometry +80+0     -composite \
       "png/NZ6144.png[2072x60+4700+12336]"  -geometry +80+3208  -composite \
       "png/NZ6144.png[80x3148+427+5500]"    -geometry +0+60     -composite \
       "png/NZ6144.png[80x3148+7999+5500]"   -geometry +2152+60  -composite \
   -font 'Helvetica-Bold' \
   -pointsize 16 \
   -annotate +80+3325 "$name"  \
   -font 'Helvetica' \
   -pointsize 8 \
   -annotate +1500+3320 "from $source. Not to be used for navigation." \
   "$name.png"

