#! /bin/sh

charts="NZ63 NZ632 NZ6321 NZ6321_1 NZ6324 NZ6324_1"

for c in $charts ; do
   echo $c
   kapfile=/usr/local/share/charts/LINZ/NewZealand/$c.kap
   cp "$kapfile" .
   gdal_translate -of PNG "$c.kap" "$c.png"
   
done

